# Generated by Django 5.2.6 on 2025-09-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_b64',
            field=models.TextField(null=True),
        ),
    ]
