# Generated by Django 5.2.6 on 2025-09-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productimage_image_url_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("clothing", "clothing"),
                    ("electronics", "electonics"),
                    ("sports", "sports"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
