# Generated by Django 5.2.6 on 2025-10-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='github_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
