# Generated by Django 5.2.6 on 2025-11-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productimage_github_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
