# Generated by Django 5.2.6 on 2025-11-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_weight_product_sizes'),
        ('vendors', '0014_auto_20251112_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('vendor', 'sku')},
        ),
    ]
