# Generated by Django 5.2.6 on 2025-11-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_sku_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
