# Generated by Django 5.2.6 on 2025-11-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
