# Generated by Django 5.2.6 on 2025-12-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_is_active_alter_product_is_archived_and_more'),
        ('vendors', '0027_remove_vendor_vendors_ven_busines_8f708e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'is_archived', '-created_at'], name='products_pr_vendor__22a642_idx'),
        ),
    ]
