# Generated by Django 5.2.6 on 2025-12-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_is_active_alter_product_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_vendor__22a642_idx',
        ),
    ]
