# Generated by Django 5.2.6 on 2025-12-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_products_pr_vendor__22a642_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_vendor__30726b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_vendor__8ccfc3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_vendor__90e4b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_50f5f1_idx',
        ),
    ]
