# Generated by Django 5.2.6 on 2025-11-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_title_event_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventanalytics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventanalytics',
            name='event',
        ),
        migrations.DeleteModel(
            name='CampaignLog',
        ),
        migrations.DeleteModel(
            name='EventAnalytics',
        ),
    ]
