# Generated by Django 5.2.6 on 2025-10-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='registered_at',
            new_name='created_at',
        ),
    ]
