# Generated by Django 5.2.6 on 2025-11-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_phone', models.CharField(db_index=True, max_length=20)),
                ('items', models.JSONField(default=list)),
                ('total_amount', models.FloatField()),
                ('paid_amount', models.FloatField(default=0)),
                ('pending_amount', models.FloatField(default=0)),
                ('is_udhaari', models.BooleanField(default=False)),
                ('invoice_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
