# Generated by Django 5.2.6 on 2025-11-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_invoice'),
        ('vendors', '0018_vendor_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='vendors.vendor'),
            preserve_default=False,
        ),
    ]
