# Generated by Django 5.2.6 on 2025-11-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_invoicechangelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceHistory',
        ),
    ]
