# Generated by Django 5.2.6 on 2025-11-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_invoice_is_locked_alter_invoicechangelog_change_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermessage',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='CustomerMessage',
        ),
    ]
