# Generated by Django 5.2.6 on 2025-11-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_customermessage_vendor_delete_activitylog_and_more'),
        ('vendors', '0018_vendor_geolocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('vendor', 'phone')},
        ),
    ]
