# Generated by Django 5.2.6 on 2025-12-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bought',
            field=models.IntegerField(default=0),
        ),
    ]
