# Generated by Django 5.2.6 on 2025-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicechangelog',
            name='action_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicechangelog',
            name='action_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoicechangelog',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
