# Generated by Django 5.2.6 on 2025-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_invoicechangelog_action_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicechangelog',
            name='action_description',
        ),
        migrations.RemoveField(
            model_name='invoicechangelog',
            name='action_title',
        ),
        migrations.RemoveField(
            model_name='invoicechangelog',
            name='payment_details',
        ),
        migrations.AlterField(
            model_name='invoicechangelog',
            name='change_type',
            field=models.CharField(choices=[('create', 'Invoice Created'), ('update', 'Invoice Updated'), ('payment', 'Payment Added'), ('delete', 'Invoice Deleted'), ('status', 'Status Change')], default='update', max_length=50),
        ),
    ]
