# Generated by Django 5.2.6 on 2025-12-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_invoicechangelog_action_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicechangelog',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicechangelog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoicechangelog',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
