# Generated by Django 5.2.6 on 2025-12-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_invoicechangelog_device_info_and_more"),
        ("vendors", "0018_vendor_geolocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="pending_amount",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["vendor", "invoice_date"], name="dashboard_i_vendor__0e36a2_idx"
            ),
        ),
    ]
