# Generated by Django 5.2.6 on 2025-12-05 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_invoice_invoice_date_and_more'),
        ('vendors', '0019_alter_event_options_alter_vendor_business_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_udhaari',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pending_amount',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicechangelog',
            name='change_type',
            field=models.CharField(choices=[('create', 'Invoice Created'), ('update', 'Invoice Updated'), ('payment', 'Payment Added'), ('delete', 'Invoice Deleted'), ('status', 'Status Change')], db_index=True, default='update', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['vendor', 'is_active'], name='dashboard_c_vendor__be93ce_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['vendor', 'phone'], name='dashboard_c_vendor__e9aa37_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['vendor', 'email'], name='dashboard_c_vendor__d9ca80_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vendor', 'is_udhaari'], name='dashboard_i_vendor__2ba04e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vendor', 'pending_amount'], name='dashboard_i_vendor__2ee4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vendor', 'customer_phone'], name='dashboard_i_vendor__fe2176_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vendor', '-created_at'], name='dashboard_i_vendor__5dbf51_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicechangelog',
            index=models.Index(fields=['invoice', '-created_at'], name='dashboard_i_invoice_afabb1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicechangelog',
            index=models.Index(fields=['vendor', 'change_type'], name='dashboard_i_vendor__9f259e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicechangelog',
            index=models.Index(fields=['vendor', '-created_at'], name='dashboard_i_vendor__6faf93_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['invoice', '-created_at'], name='dashboard_i_invoice_f526db_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('vendor', 'email'), name='uniq_vendor_email'),
        ),
    ]
