# Generated by Django 5.2.6 on 2025-12-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_customer_email_alter_customer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='dashboard_c_vendor__d9ca80_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
