# Generated by Django 5.2.6 on 2025-12-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_customer_dashboard_c_vendor__d9ca80_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='uniq_vendor_email',
        ),
    ]
