# Generated by Django 5.2.6 on 2025-12-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_customer_uniq_vendor_email'),
        ('vendors', '0027_remove_vendor_vendors_ven_busines_8f708e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='dashboard_c_vendor__e9aa37_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_udhaari',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicechangelog',
            name='change_type',
            field=models.CharField(choices=[('create', 'Invoice Created'), ('update', 'Invoice Updated'), ('payment', 'Payment Added'), ('delete', 'Invoice Deleted'), ('status', 'Status Change')], default='update', max_length=50),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['vendor', '-created_at'], name='dashboard_c_vendor__eb28c6_idx'),
        ),
    ]
