# Generated by Django 5.2.6 on 2025-12-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_customer_dashboard_c_vendor__e9aa37_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='dashboard_c_vendor__be93ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='dashboard_i_vendor__2ba04e_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicechangelog',
            name='dashboard_i_vendor__9f259e_idx',
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
