# Generated by Django 5.2.6 on 2025-11-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backgroundtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundtask',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='backgroundtask',
            name='result_url',
        ),
        migrations.AddField(
            model_name='backgroundtask',
            name='result_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundtask',
            name='task_type',
            field=models.CharField(choices=[('IMAGE_UPLOAD', 'Image Upload'), ('PRODUCT_CREATION', 'Product Creation')], max_length=50),
        ),
    ]
