# Generated by Django 5.2.6 on 2025-11-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_backgroundtask_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundtask',
            name='upload_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
