# Generated by Django 5.2.6 on 2025-11-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backgroundtask_upload_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='task_type',
            field=models.CharField(choices=[('IMAGE_UPLOAD', 'Image Upload'), ('PRODUCT_CREATION', 'Product Creation'), ('TELEGRAM_LINK', 'Telegram Link')], max_length=50),
        ),
    ]
