# Generated by Django 5.2.6 on 2025-11-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_subscription_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='after_webhook_called',
            field=models.BooleanField(default=False),
        ),
    ]
