# Generated by Django 5.2.6 on 2025-11-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_after_webhook_called'),
        ('vendors', '0009_vendor_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='razorpay_signature',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['razorpay_payment_id'], name='subscriptio_razorpa_e242f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_payment_id__isnull', False), ('razorpay_signature__isnull', False)), fields=('razorpay_payment_id', 'razorpay_signature'), name='unique_payment_signature_combo'),
        ),
    ]
