# Generated by Django 5.2.6 on 2025-12-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_paymenttransaction_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount in paise'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_in_paise',
            field=models.PositiveIntegerField(help_text='Price in paise for Razorpay'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='sync_limit',
            field=models.PositiveIntegerField(default=10, help_text='Number of syncs allowed per month'),
        ),
    ]
