# Generated by Django 5.2.6 on 2025-12-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_paymenttransaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='subscriptio_razorpa_e242f4_idx',
        ),
    ]
