# Generated by Django 5.2.6 on 2025-12-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_paymenttransaction_subscriptio_razorpa_e242f4_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='subscriptio_vendor__3c3cc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='subscriptio_razorpa_9333dd_idx',
        ),
    ]
