"""
Django settings for marketplace project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
import secrets as secrets_module

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


local_env = BASE_DIR / ".env"


external_env = Path("/home/ec2-user/.env.prod")

if local_env.exists():
    load_dotenv(local_env)
    print("📌 Loaded environment from local .env")
elif external_env.exists():
    load_dotenv(external_env)
    print("📌 Loaded environment from /home/ec2-user/deploy/.env.prod")
else:
    print("⚠️ No .env file found; relying on system environment")




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if os.getenv('ENVIRONMENT', 'development') == 'production':
        raise ValueError("DJANGO_SECRET_KEY must be set in production")
    else:
        # Auto-generate for development only
        SECRET_KEY = 'dev-only-key-' + secrets_module.token_urlsafe(50)
        print("⚠️  WARNING: Using auto-generated SECRET_KEY for development")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"


ENVIRONMENT = os.getenv("ENVIRONMENT", "development").lower()

if ENVIRONMENT == "production":
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "false").lower() == "true"
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SECURE_SSL_REDIRECT = False     
    
    
USE_REDIS = os.getenv("USE_REDIS", "false").lower() == "true"
USE_CELERY = os.getenv("USE_CELERY", "false").lower() == "true"
BIG_MACHINE = os.getenv("DO_WE_HAVE_BIG_MACHINE", "false").lower() == "true"    


# ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

ALLOWED_HOSTS = [
    "api.fordgeindia.online",
    "13.234.203.82",
    "localhost",
    "127.0.0.1",
]
if DEBUG:
    ALLOWED_HOSTS.append(os.getenv("TEMPORARY_URL"))
    print("Added TEMPORARY_URL to ALLOWED_HOSTS",ALLOWED_HOSTS)

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "https://api.fordgeindia.online"
]





# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'cloudinary',
    'cloudinary_storage',
]

LOCAL_APPS = [
    'apps.users',
    'apps.vendors',
    'apps.products',
    'apps.dashboard',
    'apps.portfolio',
    'apps.subscriptions',
    'apps.core',
    
]
INSTALLED_APPS = INSTALLED_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Keep only once, at top
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',  # Keep only once
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',  # Only in DEBUG
]

if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')
    INSTALLED_APPS.append('silk')
    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')
    MIDDLEWARE.insert(0, 'silk.middleware.SilkyMiddleware')
    # MIDDLEWARE.append('silk.middleware.SilkyMiddleware')

INTERNAL_IPS = ['127.0.0.1']

ROOT_URLCONF = 'marketplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'marketplace.wsgi.application'


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}




AWS_ACCESS_KEY_ID=os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY=os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME=os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME=os.getenv("AWS_S3_REGION_NAME")

CLOUDINARY_STORAGE = {
    "CLOUDINARY_CLOUD_NAME": os.getenv("CLOUDINARY_CLOUD_NAME"),
    "CLOUDINARY_API_KEY": os.getenv("CLOUDINARY_API_KEY"),
    "CLOUDINARY_API_SECRET": os.getenv("CLOUDINARY_API_SECRET"),
}





UPLOAD_PROVIDER = "cloudinary"  # or 's3'


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES': ( this class by default make request to db at each call to verify user 
    #     'rest_framework_simplejwt.authentication.JWTAuthentication',
    # ),
    
    'DEFAULT_AUTHENTICATION_CLASSES': ( # added this cause it caches the data of user and wont make request at every request
        'apps.core.authentication.CachedJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'EXCEPTION_HANDLER': 'apps.core.exceptions_.exceptions.custom_exception_handler'
}



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=3),  # Reduced from 10 hours for security
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,  # Track login activity
    # Custom token serializer with vendor_id claim
    'TOKEN_OBTAIN_SERIALIZER': 'apps.users.serializers.CustomTokenObtainPairSerializer',
}
    

FRONTEND_ORIGIN = os.getenv("FRONTEND_ORIGIN")


frontend_origins = os.getenv("FRONTEND_ORIGINS", "")

CORS_ALLOWED_ORIGINS=["https://d2pwo63dqka82f.cloudfront.net","http://localhost:5173","https://admin.fordgeindia.online","https://www.admin.fordgeindia.online"]

CSRF_TRUSTED_ORIGINS = ["https://d2pwo63dqka82f.cloudfront.net","http://localhost:5173","https://admin.fordgeindia.online","https://www.admin.fordgeindia.online"]


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_ALL_ORIGINS = ENVIRONMENT != "production"

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http?:\/\/([a-zA-Z0-9-]+)\.localhost:3000$",  # For local development
    # r"^https?:\/\/([a-zA-Z0-9-]+)\.yourdomain\.com$", # For production
]

# dont know how this will work but here i have just added this let see 
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB


DEFAULT_SYNC_COUNT = os.getenv("DEFAUTL_SYNC_COUNT")
FRONTEND_BASE_PORTFOLIO_PREVIEW = os.getenv("FRONTEND_BASE_PORTFOLIO_PREVIEW")
FRONTEND_PORTFOLIO_PORT = os.getenv("FRONTEND_PORTFOLIO_PORT",3000) 


RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET')
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET')  # For webhook signature verification



TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_BOT_USERNAME = os.getenv('TELEGRAM_BOT_USERNAME')
JWT_SECRET = os.getenv('JWT_SECRET')
TELEGRAM_WEBHOOK_SECRET = os.getenv('TELEGRAM_WEBHOOK_SECRET')


# # Redis running inside Docker, exposed to host on port 6380
# REDIS_URL = "redis://localhost:6380/0"

# # Celery uses Redis as both broker and result backend
# CELERY_BROKER_URL = REDIS_URL
# CELERY_RESULT_BACKEND = REDIS_URL

# # Optional tuning
# CELERY_TASK_TRACK_STARTED = True
# CELERY_TASK_TIME_LIMIT = 30 * 60
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'


# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": REDIS_URL,
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }


# REDIS_CACHE_DEFAULT_TTL = 60 * 60 * 5  # 5 hours



##############################################
# DYNAMIC REDIS / CELERY CONFIGURATION
##############################################

USE_REDIS = os.getenv("USE_REDIS", "false").lower() == "true"
USE_CELERY = os.getenv("USE_CELERY", "false").lower() == "true"
BIG_MACHINE = os.getenv("DO_WE_HAVE_BIG_MACHINE", "false").lower() == "true"

# Auto-disable Redis + Celery on weak machines
REDIS_ACTIVE = USE_REDIS 
CELERY_ACTIVE = USE_CELERY and BIG_MACHINE

REDIS_HOST  = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT  = os.getenv("REDIS_PORT", "6379") 

if REDIS_ACTIVE:
    # Example: redis://localhost:6380/0
    REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"

    print(" Redis ENABLED → Using RedisCache")
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        }
    }

else:
    print(" Redis DISABLED → Using LocMemCache")
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-saas-cache",
        }
    }



##############################################
# CELERY CONFIG (BROKER + BACKEND)
##############################################

if CELERY_ACTIVE:
    print(" Celery ENABLED → Using Redis broker")
    
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL

    CELERY_TASK_TRACK_STARTED = True
    CELERY_TASK_TIME_LIMIT = 30 * 60
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'

else:
    print("Celery DISABLED → Running tasks synchronously")
    
    CELERY_BROKER_URL = None
    CELERY_RESULT_BACKEND = None



# Add proper logging configuration:
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'] if not DEBUG else ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

BANNER_IMAGES = [
    "https://vendor-products-media.s3.ap-south-1.amazonaws.com/defaults/73faa2222087589.67e00aed92f9f.gif",
    
    ]