# Generated by Django 5.2.6 on 2025-09-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
