# Generated by Django 5.2.6 on 2025-09-07 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
        ('vendors', '0002_vendor_business_type_vendor_gstin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='vendors.vendor'),
            preserve_default=False,
        ),
    ]
