# Generated by Django 5.2.6 on 2025-09-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_vendorprofile_business_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
