# Generated by Django 5.2.6 on 2025-11-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_address_zip_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
