# Generated by Django 5.2.6 on 2025-11-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_customerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
