# Generated by Django 5.2.6 on 2025-12-07 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_address_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
    ]
