# Generated by Django 5.2.6 on 2025-12-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_address_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='users_addre_city_08b5d8_idx',
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('admin', 'Admin')], default='vendor', max_length=20),
        ),
    ]
