# Generated by Django 5.2.6 on 2025-12-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_address_users_addre_city_08b5d8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='users_addre_user_id_194804_idx',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='idx_address_user_type',
        ),
    ]
