# Generated by Django 5.2.6 on 2025-09-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('other', 'Other')], default='other', max_length=25),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
