# Generated by Django 5.2.6 on 2025-09-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_business_type_vendor_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
