# Generated by Django 5.2.6 on 2025-09-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_vendor_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='business_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
