# Generated by Django 5.2.6 on 2025-10-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_vendor_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_name_slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
