# Generated by Django 5.2.6 on 2025-11-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_vendor_business_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
