# Generated by Django 5.2.6 on 2025-11-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vendor_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
