# Generated by Django 5.2.6 on 2025-11-11 18:01

import apps.vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_vendor_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='secret',
            field=models.CharField(blank=True, default=apps.vendors.models.generate_secret, max_length=10, null=True),
        ),
    ]
