# Generated by Django 5.2.6 on 2025-11-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_vendor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='secret_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
