# Generated by Django 5.2.6 on 2025-11-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_vendor_secret_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='business_phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
