# Generated by Django 5.2.6 on 2025-11-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_alter_vendor_business_phone'),
    ]

    operations = [
    ]
