# Generated by Django 5.2.6 on 2025-11-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_auto_20251112_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
