# Generated by Django 5.2.6 on 2025-11-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_event_postertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='postertemplate',
            name='html_template',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postertemplate',
            name='design_schema',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
