# Generated by Django 5.2.6 on 2025-11-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_postertemplate_html_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='geolocation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
