# Generated by Django 5.2.6 on 2025-12-05 08:11

import apps.vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_vendor_geolocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_email',
            field=models.EmailField(db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_phone',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='secret',
            field=models.CharField(blank=True, db_index=True, default=apps.vendors.models.generate_secret, max_length=10, null=True),
        ),
    ]
