# Generated by Django 5.2.6 on 2025-12-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_alter_event_options_alter_vendor_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='handle',
            field=models.CharField(blank=True, db_index=True, max_length=130, null=True, unique=True),
        ),
    ]
