# Generated by Django 5.2.6 on 2025-12-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_vendor_handle_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_ven_busines_8f708e_idx',
            old_name='vendors_ven_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_ven_busines_57b1f2_idx',
            old_name='vendors_ven_busines_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_ven_handle_96cf29_idx',
            old_name='vendors_ven_handle_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_ven_is_acti_700cdc_idx',
            old_name='vendors_ven_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_ven_created_c4e3ec_idx',
            old_name='vendors_ven_created_idx',
        ),
    ]
