# Generated by Django 5.2.6 on 2025-12-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0022_rename_vendors_ven_busines_idx_vendors_ven_busines_8f708e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='business_name_slug',
        ),
    ]
