# Generated by Django 5.2.6 on 2025-12-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_remove_vendor_business_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_started_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
