# Generated by Django 5.2.6 on 2025-12-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0024_vendor_business_categories_vendor_business_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.IntegerField(default=0)),
                ('active_products', models.IntegerField(default=0)),
                ('inactive_products', models.IntegerField(default=0)),
                ('total_customers', models.IntegerField(default=0)),
                ('active_customers', models.IntegerField(default=0)),
                ('inactive_customers', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='vendors.vendor')),
            ],
        ),
    ]
