# Generated by Django 5.2.6 on 2025-12-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0025_vendorstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorstats',
            name='active_customers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorstats',
            name='active_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorstats',
            name='inactive_customers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorstats',
            name='inactive_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorstats',
            name='total_customers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorstats',
            name='total_products',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
