# Generated by Django 5.2.6 on 2025-12-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0026_alter_vendorstats_active_customers_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendors_ven_busines_8f708e_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendors_ven_busines_57b1f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendors_ven_handle_96cf29_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendors_ven_is_acti_700cdc_idx',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
