# Generated by Django 5.2.6 on 2025-12-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0027_remove_vendor_vendors_ven_busines_8f708e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendors_ven_created_c4e3ec_idx',
        ),
    ]
