# Generated by Django 5.2.6 on 2025-12-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0028_remove_vendor_vendors_ven_created_c4e3ec_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
