# Generated by Django 5.2.6 on 2025-12-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0029_vendor_google_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='google_maps_url',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
