# Generated by Django 5.2.6 on 2026-01-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0030_alter_vendor_google_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
