# Generated by Django 5.2.6 on 2025-11-28 15:03

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_delete_productimage'),
        ('vendors', '0018_vendor_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('preview_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('theme_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Display name for portfolio', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Your Vision Our Product', help_text='Short tagline/slogan', max_length=300)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('business_name_slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('about_us', models.TextField(blank=True)),
                ('our_story', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True, default="To provide exceptional products and services that exceed our customers' expectations.")),
                ('vision', models.TextField(blank=True, default='To become the leading provider in our industry, known for innovation and customer satisfaction.')),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('banner_image', models.URLField(blank=True, max_length=500, null=True)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(default='My Portfolio', max_length=255)),
                ('carousel_images', models.JSONField(blank=True, default=list)),
                ('theme_color', models.CharField(default='#141414', max_length=7)),
                ('accent_color', models.CharField(default='#ffffff', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('font_family', models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat')], default='Inter', max_length=50)),
                ('layout_style', models.CharField(choices=[('modern', 'Modern Grid'), ('classic', 'Classic List'), ('masonry', 'Masonry Layout'), ('minimal', 'Minimal Cards')], default='modern', max_length=20)),
                ('portfolio_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('show_pricing', models.BooleanField(default=True)),
                ('show_stock_status', models.BooleanField(default=True)),
                ('show_contact_form', models.BooleanField(default=True)),
                ('show_social_links', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=True)),
                ('show_gallery', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_carousel', models.BooleanField(default=False)),
                ('want_to_show_on_platform', models.BooleanField(default=False)),
                ('custom_domain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for advanced styling')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_products', models.ManyToManyField(blank=True, related_name='featured_in_portfolios', to='products.product')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSyncPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_syncs_per_day', models.PositiveIntegerField(default=5)),
                ('used_syncs_today', models.PositiveIntegerField(default=0)),
                ('extra_syncs_available', models.PositiveIntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_plan', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='portfolio.portfolio')),
                ('products', models.ManyToManyField(related_name='portfolio_collections', to='products.product')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('portfolio', 'slug')},
            },
        ),
    ]
