# Generated by Django 5.2.6 on 2025-11-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('vendors', '0018_vendor_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliosyncplan',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfoliosyncplan',
            name='vendor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sync_plan', to='vendors.vendor'),
            preserve_default=False,
        ),
    ]
