# Generated by Django 5.2.6 on 2025-10-28 12:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfoliocollection_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocollection',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
