# Generated by Django 5.2.6 on 2025-11-28 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfoliosyncplan_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliosyncplan',
            name='vendor',
        ),
        migrations.AddField(
            model_name='portfoliosyncplan',
            name='portfolio',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sync_plan', to='portfolio.portfolio'),
            preserve_default=False,
        ),
    ]
