# Generated by Django 5.2.6 on 2025-11-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfoliocollection_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='address',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='whatsapp_number',
        ),
    ]
