# Generated by Django 5.2.6 on 2025-12-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfoliosyncplan_vendor_and_more'),
        ('products', '0014_alter_product_is_active_alter_product_is_archived_and_more'),
        ('vendors', '0019_alter_event_options_alter_vendor_business_email_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['vendor', 'is_public'], name='portfolio_p_vendor__d272b5_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['is_featured'], name='portfolio_p_is_feat_120311_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['custom_domain'], name='portfolio_p_custom__f6ab8a_idx'),
        ),
    ]
