# Generated by Django 5.2.6 on 2025-12-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_portfolio_p_vendor__d272b5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_p_vendor__d272b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_p_is_feat_120311_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_p_custom__f6ab8a_idx',
        ),
    ]
