# Generated by Django 5.2.6 on 2025-11-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolio_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='business_name_slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
