# Generated by Django 5.2.6 on 2025-12-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_portfolio_portfolio_p_vendor__d272b5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocollection',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
