# Generated by Django 5.2.6 on 2025-11-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_business_name_slug'),
        ('vendors', '0009_vendor_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSyncPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_syncs_per_day', models.PositiveIntegerField(default=3)),
                ('used_syncs_today', models.PositiveIntegerField(default=0)),
                ('extra_syncs_available', models.PositiveIntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_plan', to='vendors.vendor')),
            ],
        ),
    ]
