# Generated by Django 5.2.6 on 2025-11-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfoliosyncplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosyncplan',
            name='allowed_syncs_per_day',
            field=models.PositiveIntegerField(default='10'),
        ),
    ]
