# Generated by Django 5.2.6 on 2025-12-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfoliocollection_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='handle',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
