# Generated by Django 5.2.6 on 2025-12-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='business_name_slug',
        ),
    ]
