# Generated by Django 5.2.6 on 2025-11-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_portfoliosyncplan_allowed_syncs_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosyncplan',
            name='allowed_syncs_per_day',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
