# Generated by Django 5.2.6 on 2025-12-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_portfolio_business_name_slug'),
        ('products', '0015_alter_product_is_active_alter_product_is_archived_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='portfoliocollection',
            index=models.Index(fields=['portfolio', 'order', 'name'], name='portfolio_p_portfol_57a13f_idx'),
        ),
    ]
