# Generated by Django 5.2.6 on 2025-11-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfoliosyncplan_allowed_syncs_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='carousel_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
