# Generated by Django 5.2.6 on 2025-11-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_portfolio_carousel_images_portfolio_is_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
    ]
