# Generated by Django 5.2.6 on 2025-12-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_portfoliocollection_portfolio_p_portfol_57a13f_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='portfoliocollection',
            name='portfolio_p_portfol_57a13f_idx',
        ),
    ]
