# Generated by Django 5.2.6 on 2025-11-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_portfolio_portfolio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='banner_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
