# Generated by Django 5.2.6 on 2025-11-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_portfolio_banner_image_alter_portfolio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='accent_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='theme_color',
            field=models.CharField(default='#141414', max_length=7),
        ),
    ]
