# Generated by Django 5.2.6 on 2025-11-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_portfolio_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='mission',
            field=models.TextField(blank=True, default="To provide exceptional products and services that exceed our customers' expectations."),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='vision',
            field=models.TextField(blank=True, default='To become the leading provider in our industry, known for innovation and customer satisfaction.'),
        ),
    ]
