# Generated by Django 5.2.6 on 2025-11-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_portfolio_mission_alter_portfolio_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='tagline',
            field=models.CharField(blank=True, default='Your Vision Our Product', help_text='Short tagline/slogan', max_length=300),
        ),
    ]
