# Generated by Django 5.2.6 on 2025-11-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_portfolio_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliocontactinquiry',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfoliocontactinquiry',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='portfoliosection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='portfoliosection',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfoliotestimonial',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioAnalytics',
        ),
        migrations.DeleteModel(
            name='PortfolioContactInquiry',
        ),
        migrations.DeleteModel(
            name='PortfolioSection',
        ),
        migrations.DeleteModel(
            name='PortfolioTestimonial',
        ),
    ]
